
["Other Settings"]
	#False for Multiplicative, I don't know why you would want Flat but here it is
	"Bonus is Flat" = false

["Spartan Weaponry"]
	#Set to 0 for no bonus
	"Heavy Crossbows" = ["iron*2", "diamond*3", "netherite*4", "copper*1.5", "tin*1.75", "bronze*2", "steel*2.5", "silver*1.5", "invar*2.2", "platinum*3.5", "electrum*2", "nickel*2", "lead*2"]
	#Set to 0 for no bonus
	Longbows = ["iron*2", "diamond*3", "netherite*4", "copper*1.5", "tin*1.75", "bronze*2", "steel*2.5", "silver*1.5", "invar*2.2", "platinum*3.5", "electrum*2", "nickel*2", "lead*2"]

["Custom Entries"]
	#'material*amount'
	"Custom Longbows/Crossbows" = ["ironwood*2", "fiery*4", "steeleaf*3", "knightly*3"]

